max_width = 80
reorder_imported_names = true
reorder_imports = true
take_source_hints = false

fn_args_layout = "Block"
array_layout = "Block"
control_style = "Rfc"
where_style = "Rfc"
generics_indent = "Block"
fn_call_style = "Block"
